// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robotMain;

import subsystems.DriveType;

import commands.*;
import edu.wpi.first.wpilibj.Joystick;
import edu.wpi.first.wpilibj.buttons.Button;
import edu.wpi.first.wpilibj.buttons.JoystickButton;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;


/**
 * This class is the glue that binds the controls on the physical operator
 * interface to the commands and command groups that allow control of the robot.
 */
public class OI {

    private Joystick leftJoystick;
    private Joystick rightJoystick;

    private Button setTankButton;
    private Button setArcade1Button;
    private Button setArcade2Button;

    public OI() {
        leftJoystick = new Joystick(RobotMap.leftJoystickPort);
        rightJoystick = new Joystick(RobotMap.rightJoystickPort);
        
        setTankButton = new JoystickButton (rightJoystick, 12);
        setTankButton.whenPressed(new DriveTypeCommand(DriveType.TANK));
        
        setArcade1Button = new JoystickButton (rightJoystick, 11);
        setArcade1Button.whenPressed(new DriveTypeCommand(DriveType.ARCADE_1));
        
        setArcade2Button = new JoystickButton (rightJoystick, 10);
        setArcade2Button.whenPressed(new DriveTypeCommand(DriveType.ARCADE_2));
    }

    public Joystick getLeftJoystick() {
        return leftJoystick;
    }

    public Joystick getRightJoystick() {
        return rightJoystick;
    }
}

