// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package robot;


/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
	public static int leftJoystickPort = 1;
	public static int rightJoystickPort = 0;
	
	public static int gamepadPort = 2;
	public static int gamepadLX = 0;
	public static int gamepadLY = 1;
	public static int gamepadLT = 2;
	public static int gamepadRT = 3;
	public static int gamepadRX = 4;
	public static int gamepadRY = 5;
	
	public static int leftTalon1Port = 0;
	public static int rightTalon1Port = 1;
}
